#include <stdio.h>
#include <math.h>
#include <assert.h>
#include <stdlib.h>
#include "poly.h"
#include <string.h>



// Generate legendre polynomials
// **P is a pointer to and array of POLYNOMIALS X COEFICIENTS.
// degree is a flag to stop when the first polynomial generated by this functions reach that degree (with ax^n with a!= 0).
void generate_legendre_poly(double P[MAX_LEGENDRE_POLYNOMIALS][POLYNOMIAL_MAX_COEFICIENTS], int degree){
    // (j+1)P_{j+1} = (2j+1)xP_j - jP_{j-1}
    P[0][0]=P[1][1]=1;
    for(int j = 1; j<=degree; j++){
        // 1x^0, x^1, ...x^2..., ... // first j = 1, because we know, no matter how, 1, and x are the first ones.
        double poly_aux1[POLYNOMIAL_MAX_COEFICIENTS] = { 0, 2*j+1 }; // (2j+1)x = [0, 2*j+1, 0, 0, ...]
        double poly_aux2[POLYNOMIAL_MAX_COEFICIENTS] = {-j}; 
        double poly_aux3[POLYNOMIAL_MAX_COEFICIENTS] = {1/(j+1.)}; 
        double P_temp1[POLYNOMIAL_MAX_COEFICIENTS], P_temp2[POLYNOMIAL_MAX_COEFICIENTS], P_temp3[POLYNOMIAL_MAX_COEFICIENTS];
        poly_mult(poly_aux1, P[j], P_temp1);
        poly_mult(poly_aux2, P[j-1], P_temp2);
        poly_add(P_temp1, P_temp2, P_temp3);
        poly_mult(poly_aux3, P_temp3, P[j+1]);
    }
////    printf("GENERATE LEGENDRE POLYNOMIALS\n");
////    for(int o=0; o<MAX_LEGENDRE_POLYNOMIALS; o++){
////        for(int p=0; p< POLYNOMIAL_MAX_COEFICIENTS; p++){
////            if(P[o][p] != 0)
////                printf("%.2lfx^%d + ", P[o][p], p);
////        }
////        printf("\n");
////    }
////    puts("\nEND GENERATE..\n");
}

// Legendre P_n is odd if n is odd, and even if n is even.
// http://hyperphysics.phy-astr.gsu.edu/hbase/Math/legend.html
//
// P_n has n roots
// https://books.google.com.br/books?id=qlNJAYwmfTcC&pg=PA114&dq=legendre+polynomials+roots&hl=en&ei=2MzxTKGrKc7bngeZuJTCCw&sa=X&oi=book_result&ct=result&redir_esc=y#v=onepage&q=legendre%20polynomials%20roots&f=false
//



int main(void){
    double lege_poly_coef[MAX_LEGENDRE_POLYNOMIALS][POLYNOMIAL_MAX_COEFICIENTS] = {0};
    generate_legendre_poly(lege_poly_coef, DEGREE_WANTED+1);
////    printf("legendre polynomials:\n");
////    char s[1000]={0};
////    for(int o=0; o<MAX_LEGENDRE_POLYNOMIALS; o++){
////        for(int p=0; p< POLYNOMIAL_MAX_COEFICIENTS; p++){
////            char summands[200]={'\0'};
////            if(lege_poly_coef[o][p] != 0){
////                sprintf(summands, "%.2lfx^%d +", lege_poly_coef[o][p], p);
////                strcat(s, summands);
////            }
////        }
////
////        s[strlen(s)] = '\0';
////        s[strlen(s)-1] = '\n';
////    }
////    printf("HERE\n%s\n", s);
    printf("MAIN\n");
    for(int o=0; o<MAX_LEGENDRE_POLYNOMIALS; o++){
        for(int p=0; p< POLYNOMIAL_MAX_COEFICIENTS; p++){
            if(lege_poly_coef[o][p] != 0)
                printf("%.2lfx^%d + ", lege_poly_coef[o][p], p);
        }
        printf("\n");
    }
    puts("\nEND GENERATE..\n");
    double x[DEGREE_WANTED]={0};
    double a=-1;
    double b=+1;
    double x_beginning_I = a; // begining and end of the interval
    double delta_x = (b-a)/DEGREE_WANTED;


    for(int i=0; i < DEGREE_WANTED; i++ ){
        x[i] = newton_raphson(x_beginning_I, x_beginning_I+delta_x, lege_poly_coef[DEGREE_WANTED]);
        x_beginning_I += delta_x;
    }
    for(int k=0; k<DEGREE_WANTED; k++){
        printf("x[%d]=%lf \n", k, x[k]);
    }

    /*
    for(int i=0; i<DEGREE_WANTED+1; i++){
        for(int j=0; j<POLYNOMIAL_MAX_COEFICIENTS; j++){
            if(lege_poly_coef[i][j] != 0)
                printf("%.2lfx^%d +", lege_poly_coef[i][j], j);
        }
        printf("\\\\\n");
    }*/
    
}


